### ISSUE TITLE
How does parallelism work in ekam?

### ISSUE THREAD

**Issue by jgarvin** [sandstorm-io/ekam#68]
If you're waiting to decide what to build based on what files programs try to open, usually you will only see one file request at a time, since people call `open` with one filename at a time. And you must block, because presumably the application is going to need the file it tried to open to exist by the time `open` returns. So how do parallel builds work in ekam? Or is it always single threaded?

**Comment by kentonv** [comment]
Note that Ekam only intercepts open() calls from build steps it is running. So, the "application" is a compiler or linker or other build tool. Not, like, a long-running program.

When Ekam intercepts open(), it looks for an already-existing file to satisfy the open(), returning it if found. If it can't find one, then it returns the error ENOENT ("file not found"), just like open() would regularly. Meanwhile, Ekam makes a note on the side that this build step _tried_ to open the given file but couldn't find anything.

Later, if some other build step ends up producing a file that other build steps had tried to open() previously, then Ekam goes back and re-runs all those build steps. On the re-run, the open() succeeds.

This does mean that during a build, Ekam will tend to run many build steps that fail spuriously, and then has to re-run them later. This turns out not to be as bad as it sounds because tools tend to fail pretty early if a file is missing, so the spurious failures don't take up a lot of time.

If I had more time to work on Ekam, I would make it remember which files a step had depended on in the past, so that it could defer running those steps until those files show up. This way, after the first build, Ekam would rarely run steps that spuriously fail. I haven't found time to build this, though. And, these days, I don't regularly use Ekam anymore; my team switched to Bazel.

**Comment by jgarvin** [comment]
Ah thanks for the clarification
